### ISSUE TITLE
Replace MySQL by Mariadb or postgres in the config

### ISSUE THREAD

**Issue by IDerr** [ryba-io/ryba-env-metal#13]
Hi,
I think it'll be better to use mariadb instead of mysql since it is more open and installed by default in debian ( when installing mysql-server)
I don't know your opinions on that question !

**Comment by wdavidw** [comment]
Agreed, I ask @lucasbak last week to enrich the configuration file with mariadb, still waiting

**Comment by IDerr** [comment]
Or we can just replace the mysql by mariadb, that's what I use in my cluster, and it works. 
In masson, mariadb has more options than mysql ?

**Comment by lucasbak** [comment]
It works already I use it every day , juste replace masson/commons/mysql/server by Masson/commons/mariadb/server, also pour the constraints on two node so you ha HA the options ( Masson options ) are identical to MySQL concerning password configuration directory etc..

**Comment by wdavidw** [comment]
This is why I want you to enrich config.coffee with it, I dont want to spend time looking at the best way to put the config in place

**Comment by wdavidw** [comment]
@IDerr to answer your question, @lucasbak has introduced suport for ssl and ha in mariadb which mysql doesnt have

**Comment by IDerr** [comment]
Oh ok, thanks

**Comment by IDerr** [comment]
8e9d51264de26101be2f36b9bb3cf989cabe3949

**Comment by wdavidw** [comment]
Well, before closing, i wish mariadb would be working out of the box without ssl, definitely not yet ready
